version: 2
jobs:
  build:
    docker:
      - image: tommoulard/criterion:latest
    steps:
      - checkout
      - run:
          name: Setting up
          command: cd vswitch && ./configure
      - run:
          name: Unit tests
          command: cd vswitch && echo "test"
      - run:
          name: Shutting down
          command: cd vswitch && ./shutdown
